on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

name: Deploy Extension to Open VSX
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - name: Publish extension to Open VSX
        uses: HaaLeo/publish-open-vsx-github-action@master
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish extension to Visual Studio Marketplace
        uses: HaaLeo/publish-open-vsx-github-action@master
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
